# Generated by Django 4.1.6 on 2023-02-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Classes", "db_table": "Classes",},
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Levels", "db_table": "Level",},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=500)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="img/dept.png",
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Nacosbot_API.classes",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Locations", "db_table": "Location",},
        ),
        migrations.AddField(
            model_name="classes",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Nacosbot_API.level"
            ),
        ),
    ]
