# Generated by Django 4.1.6 on 2023-02-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Nacosbot_API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=500)),
                ("unit", models.IntegerField(default=2)),
                ("desc", models.CharField(max_length=1000)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Nacosbot_API.level",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Courses", "db_table": "Course",},
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=500)),
            ],
            options={"verbose_name_plural": "Semesters", "db_table": "Semester",},
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name_plural": "Lecturer Title",
                "db_table": "Lecturer Title",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="materials/")),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Nacosbot_API.level",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Nacosbot_API.semester",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Materials", "db_table": "Material",},
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "pics",
                    models.ImageField(
                        blank=True,
                        default="img/comlogo.png",
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Nacosbot_API.title",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lecturers profile",
                "db_table": "Lecturer Profile",
            },
        ),
        migrations.CreateModel(
            name="CoursesToLecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Nacosbot_API.course",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Nacosbot_API.lecturer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courses Assigned to Lecturers",
                "db_table": "Courses Assigned to Lecturers",
            },
        ),
    ]
