# Generated by Django 4.1.6 on 2023-02-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Nacosbot_API", "0003_course_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Nacosbot_API.course",
            ),
            preserve_default=False,
        ),
    ]
